version: '3'
services:
  nginx: 
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: ./nginx/images/php/Dockerfile
    volumes:
      - ./:/var/www
